onboarding-net/Models/Kurir.cs
using System.ComponentModel.DataAnnotations;

namespace onboarding_net.Models
{
    public class Kurir
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(250)]
        public string Address { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;

        public List<Item>? Items { get; set; } = null;

        public Warehouse? Warehouse { get; set; }

        public int GudangId { get; set; }


    }
}

onboarding-net/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using onboarding_net.Data;
using onboarding_net.Models;
using System;
using System.Linq;
using System.Xml.Linq;

namespace onboarding_net.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ItemController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(int? id)
        {
            IEnumerable<Item> objCategoryList = _db.Items.Where(m => m.KurirId == id);
            ViewBag.IdKurir = id;
            return View(objCategoryList);
        }

        //GET
        public IActionResult Create(int? id)
        {
            Item Data = new Item
            {
                KurirId = (int)id
            };
            return View(Data);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name,Address,KurirId,Status")] Item obj)
        {
            if (ModelState.IsValid)
            {
                _db.Items.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = obj.KurirId });
            }
            return View(obj);
        }
        //GET 
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var itemFromDb = _db.Items.Find(id);

            if (itemFromDb == null)
            {
                return NotFound();
            }

            return View(itemFromDb);
        }

        //PUT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Item obj)
        {
            if (ModelState.IsValid)
            {
                _db.Items.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = obj.KurirId });
            }
            return View(obj);     
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var itemFromDb = _db.Items.Find(id);

            if (itemFromDb == null)
            {
                return NotFound();
            }

            return View(itemFromDb);
        }

        //Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Items.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
  
            _db.Items.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index", new { id = obj.KurirId });

        }
    }
}

onboarding-net/Controllers/KurirController.cs
using ContosoUniversity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using onboarding_net.Data;
using onboarding_net.Models;
using System.Dynamic;

namespace onboarding_net.Controllers
{
    public class KurirController : Controller
    {
        private readonly ApplicationDbContext _db;

        public KurirController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Name" : "";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var obj = from s in _db.Kurir
                      select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                obj = obj.Where(s => s.Name.Contains(searchString) || s.Address.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Name":
                    obj = obj.OrderBy(s => s.Name);
                    break;
                default:
                    obj = obj.OrderBy(s => s.Address);
                    break;
            }

            int pageSize = 2;
            return View(await PaginatedList<Kurir>.CreateAsync(obj.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        /*public IActionResult Index(string? Search, int? pageNumber)
        {
            ViewData["CurrentFilter"] = Search;
            IEnumerable<Kurir> objCategoryList = _db.Kurir;
            if (!String.IsNullOrEmpty(Search))
            {
                objCategoryList = _db.Kurir.Where(k => k.Name.Contains(Search) || k.Address.Contains(Search));
            }
            int pageSize = 3;
            return View(objCategoryList.PaginatedList();
        }*/

        // GET
        public IActionResult Create()
        {
            ViewBag.Warehouse = _db.Warehouses;
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Kurir obj)
        {
            if (ModelState.IsValid)
            {
                _db.Kurir.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET 
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Kurir.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            ViewBag.Warehouse = _db.Warehouses;
            return View(categoryFromDb);
        }

        //PUT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Kurir obj)
        {
            if (ModelState.IsValid)
            {
                _db.Kurir.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Kurir.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            ViewBag.Warehouse = _db.Warehouses;
            return View(categoryFromDb);
        }

        //Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Kurir.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Kurir.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

onboarding-net/Views/Kurir/Create.cshtml
@model onboarding_net.Models.Kurir

<form asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Tambah Data Kurir</h2>
            <hr>
        </div>
        <div class="mb-3">
            <label asp-for="Name">Nama Kurir</label>
            <input asp-for="Name" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Address">Alamat Kurir</label>
            <input asp-for="Address" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="GudangId" class="control-label">Gudang</label>
            <select asp-for="GudangId" class="form-control">
                <option>Pilih Gudang...</option>
                @foreach (var item in ViewBag.Warehouse)
                {
                    <option value="@item.Id">@item.Name</option>
                }
                
            </select>
        </div>
        <br /><br />
        <button type="submit" class="btn btn-primary" style="width: 150px;">Simpan</button>
        
    </div>
</form>

onboarding-net/Views/Kurir/Delete.cshtml
@model onboarding_net.Models.Kurir

<form asp-action="Delete" method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Data Kurir</h2>
            <hr>
        </div>
        <div class="mb-3">
            <label asp-for="Name">Nama Kurir</label>
            <input asp-for="Name" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Address">Alamat Kurir</label>
            <input asp-for="Address" disabled  class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="GudangId" class="control-label">Gudang</label>
            <select disabled asp-for="GudangId" class="form-control">
                <option>Pilih Gudang...</option>
                @foreach (var item in ViewBag.Warehouse)
                {
                    <option value="@item.Id">@item.Name</option>
                }

            </select>
        </div>
        <br /><br />
        <button type="submit" class="btn btn-primary" style="width: 150px;">Hapus</button>
        <a asp-controller="Kurir" asp-action="Index" class="btn btn-secondary" style="width: 150px;">
            Kembali
        </a>
    </div>
</form>

onboarding-net/Views/Kurir/Edit.cshtml
@model onboarding_net.Models.Kurir

<form asp-action="Edit" method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Data Kurir</h2>
            <hr>
        </div>
        <div class="mb-3">
            <label asp-for="Name">Nama Kurir</label>
            <input asp-for="Name" class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Address">Alamat Kurir</label>
            <input asp-for="Address" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="GudangId" class="control-label">Gudang</label>
            <select asp-for="GudangId" class="form-control">
                <option>Pilih Gudang...</option>
                @foreach (var item in ViewBag.Warehouse)
                {
                    <option value="@item.Id">@item.Name</option>
                }

            </select>
        </div>
        <br /><br />
        <button type="submit" class="btn btn-primary" style="width: 150px;">Simpan</button>
        <a asp-controller="Kurir" asp-action="Index" class="btn btn-secondary" style="width: 150px;">
           Kembali
        </a>
    </div>
</form>

onboarding-net/Views/Kurir/Index.cshtml
@using ContosoUniversity
@model PaginatedList<onboarding_net.Models.Kurir>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="row">
        <div class="col-6">
            <h2>Daftar Kurir</h2>
        </div>
        <div class="col-6">
            <a asp-controller="Kurir" asp-action="Create" class="btn btn-primary">
                Tambah Kurir
            </a>
        </div>
    </div>

    <form asp-action="Index" method="get">
        <div class="form-actions no-color">
            <div class="input-group">
                <input type="text" class="form-control rounded" placeholder="Search" name="SearchString" value="@ViewData["CurrentFilter"]" />
                <button type="submit" class="btn btn-outline-primary">search</button>
            </div>
        </div>
    </form>
    <br /><br />
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" class="text-dark text-decoration-none">Nama Kurir</a>
                </th>
                <th>
                    Alamat Kurir
                </th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>
                        @obj.Name
                    </td>
                    <td>
                        @obj.Address
                    </td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a asp-controller="Item" asp-action="Index" asp-route-id="@obj.Id" class="btn btn-primary">Detail</a>
                            <a asp-controller="Kurir" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-warning">Edit</a>
                            <a asp-controller="Kurir" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
        Next
    </a>

</div>