onboarding-net/Controllers/KurirController.cs
using ContosoUniversity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using onboarding_net.Data;
using onboarding_net.Models;
using System.Dynamic;

namespace onboarding_net.Controllers
{
    public class KurirController : Controller
    {
        private readonly ApplicationDbContext _db;

        public KurirController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Name" : "";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var obj = from s in _db.Kurir
                      select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                obj = obj.Where(s => s.Name.Contains(searchString) || s.Address.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Name":
                    obj = obj.OrderBy(s => s.Name);
                    break;
                default:
                    obj = obj.OrderBy(s => s.Address);
                    break;
            }

            int pageSize = 2;
            return View(await PaginatedList<Kurir>.CreateAsync(obj.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        /*public IActionResult Index(string? Search, int? pageNumber)
        {
            ViewData["CurrentFilter"] = Search;
            IEnumerable<Kurir> objCategoryList = _db.Kurir;
            if (!String.IsNullOrEmpty(Search))
            {
                objCategoryList = _db.Kurir.Where(k => k.Name.Contains(Search) || k.Address.Contains(Search));
            }
            int pageSize = 3;
            return View(objCategoryList.PaginatedList();
        }*/

        // GET
        public IActionResult Create()
        {
            ViewBag.Warehouse = _db.Warehouses;
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Kurir obj)
        {
            if (ModelState.IsValid)
            {
                _db.Kurir.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET 
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Kurir.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            ViewBag.Warehouse = _db.Warehouses;
            return View(categoryFromDb);
        }

        //PUT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Kurir obj)
        {
            if (ModelState.IsValid)
            {
                _db.Kurir.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Kurir.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            ViewBag.Warehouse = _db.Warehouses;
            return View(categoryFromDb);
        }

        //Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Kurir.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Kurir.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

onboarding-net/Controllers/WarehouseController.cs
using onboarding_net.Data;
using Microsoft.AspNetCore.Mvc;
using onboarding_net.Models;
using System.Security.Policy;
using Microsoft.EntityFrameworkCore;

namespace onboarding_net.Controllers
{
    public class WarehouseController : Controller
    {
        private readonly ApplicationDbContext _db;

        public WarehouseController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Warehouse> obj = _db.Warehouses;
            return View(obj);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        public IActionResult Create(Warehouse obj)
        {
            Console.WriteLine("Masuk Awal");
            if (ModelState.IsValid)
            {
                _db.Warehouses.Add(obj);
                
                _db.SaveChanges();
                Console.WriteLine("Masuk Akhir");
                return Json("Request Success");
            }
            Console.WriteLine("Tidak Masuk");
            return Json("Request Failed");
        }

        public IActionResult Multiple()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Multiple(KurirGudang obj)
        {
            Warehouse emp = new Warehouse();
            emp.Name = obj.NameGudang;
            emp.Address = obj.AddressGudang;

            _db.Warehouses.Add(emp);
            _db.SaveChanges();

            int latestWareId = emp.Id;


            Kurir site = new Kurir();
            site.Name = obj.NameKurir;
            site.Address = obj.AddressKurir;
            site.GudangId = latestWareId;

            _db.Kurir.Add(site);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


        //GET 
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Warehouses.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //PUT
        [HttpPost]
        public IActionResult Edit(Warehouse obj)
        {
            if (ModelState.IsValid)
            {
                _db.Warehouses.Update(obj);
                _db.SaveChanges();
                return Json("Request Success");
            }
            return Json("Request Failed");
        }

        //Delete
        [HttpPost, ActionName("Delete")]
        public IActionResult Delete(Warehouse obj)
        {
            Console.WriteLine(obj.Id);
            var value = _db.Warehouses.Find(obj.Id);
            if (value == null)
            {
                return NotFound();
            }

            _db.Warehouses.Remove(value);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

    }
}

onboarding-net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GudangKece</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/onboarding_net.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GudangKece</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Kurir" asp-action="Index">Kurir</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Index">Gudang</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>